[project]
name = "video-info-downloader"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "naoyashiga", email = "" }
]
dependencies = [
    "pytube>=15.0.0",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
